// Erzeugt von scripts/ingredient-images/publish-map.mjs — nicht von Hand aendern.
// Zutatenname -> Slug unter /zutaten-marktregal/<slug>-bold.webp

export const INGREDIENT_IMAGES: Record<string, string> = {
  "Banane": "banane",
  "Berglinsen": "berglinsen",
  "Blaubeeren": "blaubeeren",
  "Brat- oder mildes Olivenöl": "bratoel",
  "Bratöl": "bratoel",
  "Currypulver": "currypulver",
  "Dinkel-Mandel-Drink": "mandelmilch",
  "Eier": "eier",
  "Erdbeeren": "erdbeeren",
  "Frühlingszwiebel": "fruehlingszwiebel",
  "Gemahlener Kreuzkümmel": "gemahlener-kreuzkuemmel",
  "Gemüsebrühe": "gemuesebruehe",
  "Gemüsebrühepulver": "gemuesebruehe",
  "getrocknete Aprikosen": "getrocknete-aprikosen",
  "Gewürznelke": "gewuerznelke",
  "Gulasch": "gulasch",
  "Holzspieße": "holzspiesse",
  "Ingwer": "ingwer",
  "Kalbsfond": "kalbsfond",
  "Karotte": "karotte",
  "Käse": "kaese",
  "Knoblauch": "knoblauch",
  "Knoblauchzehe": "knoblauchzehe",
  "Kuchen": "kuchen",
  "Lauch": "lauch",
  "Lauchzwiebel": "fruehlingszwiebel",
  "Limettensaft": "limettensaft",
  "Lorbeerblätter": "lorbeerblaetter",
  "Mandelmilch": "mandelmilch",
  "Meerrettich": "meerrettich",
  "Möhre": "moehre",
  "Nudeln": "nudeln",
  "Orangensaft": "orangensaft",
  "Pizza": "pizza",
  "Rote Linsen": "rote-linsen",
  "Salz": "salz",
  "scharfes Currypulver": "scharfes-currypulver",
  "Schmand": "schmand",
  "Schmand 150 g": "schmand",
  "schwarzer Pfeffer": "schwarzer-pfeffer",
  "Schweineschmalz": "schweineschmalz",
  "Tofu": "tofu",
  "Wacholderbeere": "wacholderbeere",
  "Wasser": "wasser",
  "Zwiebel": "zwiebel",
};

export function ingredientImage(name: string): string | null {
  const slug = INGREDIENT_IMAGES[name];
  return slug ? `/zutaten-marktregal/${slug}-bold.webp` : null;
}
