// Erzeugt von scripts/ingredient-images/publish-map.mjs — nicht von Hand aendern.
// Zutatenname -> Slug unter /zutaten-marktregal/<slug>-bold.webp

export const INGREDIENT_IMAGES: Record<string, string> = {
  "Banane": "banane",
  "Berglinsen": "berglinsen",
  "Blaubeeren": "blaubeeren",
  "Bohnen": "bohnen",
  "Brat- oder mildes Olivenöl": "bratoel",
  "Bratöl": "bratoel",
  "Butter": "butter",
  "Currypulver": "currypulver",
  "Datteln": "datteln",
  "Dinkel-Mandel-Drink": "mandelmilch",
  "Eier": "eier",
  "Erdbeeren": "erdbeeren",
  "Frischkäse": "frischkaese",
  "Frühlingszwiebel": "fruehlingszwiebel",
  "Gemahlener Kreuzkümmel": "gemahlener-kreuzkuemmel",
  "Gemüsebrühe": "gemuesebruehe",
  "Gemüsebrühepulver": "gemuesebruehe",
  "getrocknete Aprikosen": "getrocknete-aprikosen",
  "Gewürznelke": "gewuerznelke",
  "Goji Beeren": "goji-beeren",
  "Gulasch": "gulasch",
  "Gurke": "gurke",
  "Hafermilch": "hafermilch",
  "Holzspieße": "holzspiesse",
  "Ingwer": "ingwer",
  "Joghurt": "joghurt",
  "Kalbsfond": "kalbsfond",
  "Karotte": "karotte",
  "Kartoffel": "kartoffel",
  "Käse": "kaese",
  "Knoblauch": "knoblauch",
  "Knoblauchzehe": "knoblauchzehe",
  "Kokosnüsse": "kokosnuesse",
  "Kuchen": "kuchen",
  "Lachs": "lachsfilet",
  "Lachsfilet": "lachsfilet",
  "Lauch": "lauch",
  "Lauchzwiebel": "fruehlingszwiebel",
  "Limettensaft": "limettensaft",
  "Lorbeerblätter": "lorbeerblaetter",
  "Mandelmilch": "mandelmilch",
  "Meerrettich": "meerrettich",
  "Möhre": "moehre",
  "Nudeln": "nudeln",
  "Oliven": "oliven",
  "Orangensaft": "orangensaft",
  "Pizza": "pizza",
  "Rote Linsen": "rote-linsen",
  "Saft": "saft",
  "Salami": "salami",
  "Salat": "salat",
  "Salz": "salz",
  "scharfes Currypulver": "scharfes-currypulver",
  "Schmand": "schmand",
  "Schmand 150 g": "schmand",
  "schwarzer Pfeffer": "schwarzer-pfeffer",
  "Schweineschmalz": "schweineschmalz",
  "Sekt": "sekt",
  "TK-Beeren": "tk-beeren",
  "Tofu": "tofu",
  "Tomate": "tomate",
  "Wacholderbeere": "wacholderbeere",
  "Walnüsse": "walnuesse",
  "Wasser": "wasser",
  "Zwiebel": "zwiebel",
};

export function ingredientImage(name: string): string | null {
  const slug = INGREDIENT_IMAGES[name];
  return slug ? `/zutaten-marktregal/${slug}-bold.webp` : null;
}
