// Erzeugt von scripts/ingredient-images/process.py — nicht von Hand aendern.
// Zutatenname -> Dateiname unter /zutaten/<slug>.webp

export const INGREDIENT_IMAGES: Record<string, string> = {
  "Zwiebel": "zwiebel",
  "Rote Zwiebel": "rote-zwiebel",
  "Schalotte": "schalotte",
  "Frühlingszwiebel": "fruehlingszwiebel",
  "Knoblauch": "knoblauch",
  "Karotte": "karotte",
  "Möhre": "moehre",
  "Kartoffel": "kartoffel",
  "Süßkartoffel": "suesskartoffel",
  "Tomate": "tomate",
  "Cherrytomate": "cherrytomate",
  "Paprika": "paprika",
  "Zucchini": "zucchini",
  "Aubergine": "aubergine",
  "Gurke": "gurke",
  "Lauch": "lauch",
  "Staudensellerie": "staudensellerie",
  "Knollensellerie": "knollensellerie",
  "Kohlrabi": "kohlrabi",
  "Weißkohl": "weisskohl",
  "Rotkohl": "rotkohl",
  "Spitzkohl": "spitzkohl",
  "Blumenkohl": "blumenkohl",
  "Brokkoli": "brokkoli",
  "Rosenkohl": "rosenkohl",
  "Wirsing": "wirsing",
  "Spinat": "spinat",
  "Mangold": "mangold",
  "Feldsalat": "feldsalat",
  "Kopfsalat": "kopfsalat",
  "Rucola": "rucola",
  "Eisbergsalat": "eisbergsalat",
  "Romanasalat": "romanasalat",
  "Champignons": "champignons",
  "Pilze": "pilze",
  "Pfifferlinge": "pfifferlinge",
  "Kürbis": "kuerbis",
  "Pastinake": "pastinake",
  "Rote Bete": "rote-bete",
  "Radieschen": "radieschen",
  "Rettich": "rettich",
  "Fenchel": "fenchel",
  "Spargel": "spargel",
  "Grüne Bohnen": "gruene-bohnen",
  "Zuckerschoten": "zuckerschoten",
  "Ingwer": "ingwer",
  "Chilischote": "chilischote",
  "Petersilie": "petersilie",
  "Basilikum": "basilikum",
  "Schnittlauch": "schnittlauch",
  "Dill": "dill",
  "Koriander": "koriander",
  "Minze": "minze",
  "Rosmarin": "rosmarin",
  "Thymian": "thymian",
  "Salbei": "salbei",
  "Zitrone": "zitrone",
  "Limette": "limette",
  "Orange": "orange",
  "Apfel": "apfel",
  "Banane": "banane",
  "Birne": "birne",
  "Erdbeeren": "erdbeeren",
  "Himbeeren": "himbeeren",
  "Blaubeeren": "blaubeeren",
  "Weintrauben": "weintrauben",
  "Pfirsich": "pfirsich",
  "Nektarine": "nektarine",
  "Pflaume": "pflaume",
  "Kirschen": "kirschen",
  "Mango": "mango",
  "Ananas": "ananas",
  "Avocado": "avocado",
  "Wassermelone": "wassermelone",
  "Kiwi": "kiwi",
  "Datteln": "datteln",
  "Feige": "feige",
  "Granatapfel": "granatapfel",
  "Brot": "brot",
  "Vollkornbrot": "vollkornbrot",
  "Toastbrot": "toastbrot",
  "Baguette": "baguette",
  "Brötchen": "broetchen",
  "Fladenbrot": "fladenbrot",
  "Tortillas": "tortillas",
  "Wraps": "wraps",
  "Knäckebrot": "knaeckebrot",
  "Zwieback": "zwieback",
  "Croissant": "croissant",
  "Burgerbrötchen": "burgerbroetchen",
  "Rindergulasch": "rindergulasch",
  "Rinderhackfleisch": "rinderhackfleisch",
  "Gemischtes Hackfleisch": "gemischtes-hackfleisch",
  "Rinderfilet": "rinderfilet",
  "Rumpsteak": "rumpsteak",
  "Rinderbraten": "rinderbraten",
  "Schweinefilet": "schweinefilet",
  "Schweineschnitzel": "schweineschnitzel",
  "Schweinebauch": "schweinebauch",
  "Kasseler": "kasseler",
  "Hähnchenbrust": "haehnchenbrust",
  "Hähnchenschenkel": "haehnchenschenkel",
  "Hähnchenkeule": "haehnchenkeule",
  "Ganzes Hähnchen": "ganzes-haehnchen",
  "Putenbrust": "putenbrust",
  "Entenbrust": "entenbrust",
  "Milch": "milch",
  "Parmesan": "parmesan",
  "Kurkuma": "kurkuma",
};

export function ingredientImage(name: string): string | null {
  const slug = INGREDIENT_IMAGES[name];
  return slug ? `/zutaten/${slug}.webp` : null;
}
