-- AUTOMATISCH ERZEUGT von scripts/generate-ingredients-seed.mjs
-- Nicht von Hand bearbeiten: Quelle ist scripts/ingredient-seed-data.mjs.
-- Neu erzeugen mit: npm run seed:stammdaten

insert into categories (id, name, sort_order) values
  ('obst-gemuese', 'Obst & Gemüse', 10),
  ('backwaren', 'Brot & Backwaren', 20),
  ('fleisch-fisch', 'Fleisch & Fisch', 30),
  ('kuehlregal', 'Kühlregal', 40),
  ('tiefkuehl', 'Tiefkühl', 50),
  ('konserven', 'Konserven & Gläser', 60),
  ('trockenware', 'Nudeln, Reis & Trockenware', 70),
  ('backen', 'Backen & Süßes', 80),
  ('gewuerze', 'Gewürze, Öle & Saucen', 90),
  ('getraenke', 'Getränke', 100),
  ('haushalt', 'Haushalt', 110),
  ('sonstiges', 'Sonstiges', 999)
on conflict (id) do update
  set name = excluded.name, sort_order = excluded.sort_order;

-- name_norm entsteht über die Funktion der Datenbank selbst, damit sie nicht von
-- der TypeScript-Seite abweichen kann.
insert into ingredients (household_id, name_norm, display_name, category_id)
select null, normalize_ingredient_name(t.name), t.name, t.category_id
from (values
  ('Zwiebel', 'obst-gemuese'),
  ('Rote Zwiebel', 'obst-gemuese'),
  ('Schalotte', 'obst-gemuese'),
  ('Frühlingszwiebel', 'obst-gemuese'),
  ('Knoblauch', 'obst-gemuese'),
  ('Karotte', 'obst-gemuese'),
  ('Möhre', 'obst-gemuese'),
  ('Kartoffel', 'obst-gemuese'),
  ('Süßkartoffel', 'obst-gemuese'),
  ('Tomate', 'obst-gemuese'),
  ('Cherrytomate', 'obst-gemuese'),
  ('Paprika', 'obst-gemuese'),
  ('Zucchini', 'obst-gemuese'),
  ('Aubergine', 'obst-gemuese'),
  ('Gurke', 'obst-gemuese'),
  ('Lauch', 'obst-gemuese'),
  ('Staudensellerie', 'obst-gemuese'),
  ('Knollensellerie', 'obst-gemuese'),
  ('Kohlrabi', 'obst-gemuese'),
  ('Weißkohl', 'obst-gemuese'),
  ('Rotkohl', 'obst-gemuese'),
  ('Spitzkohl', 'obst-gemuese'),
  ('Blumenkohl', 'obst-gemuese'),
  ('Brokkoli', 'obst-gemuese'),
  ('Rosenkohl', 'obst-gemuese'),
  ('Wirsing', 'obst-gemuese'),
  ('Spinat', 'obst-gemuese'),
  ('Mangold', 'obst-gemuese'),
  ('Feldsalat', 'obst-gemuese'),
  ('Kopfsalat', 'obst-gemuese'),
  ('Rucola', 'obst-gemuese'),
  ('Eisbergsalat', 'obst-gemuese'),
  ('Romanasalat', 'obst-gemuese'),
  ('Champignons', 'obst-gemuese'),
  ('Pilze', 'obst-gemuese'),
  ('Pfifferlinge', 'obst-gemuese'),
  ('Kürbis', 'obst-gemuese'),
  ('Pastinake', 'obst-gemuese'),
  ('Rote Bete', 'obst-gemuese'),
  ('Radieschen', 'obst-gemuese'),
  ('Rettich', 'obst-gemuese'),
  ('Fenchel', 'obst-gemuese'),
  ('Spargel', 'obst-gemuese'),
  ('Grüne Bohnen', 'obst-gemuese'),
  ('Zuckerschoten', 'obst-gemuese'),
  ('Ingwer', 'obst-gemuese'),
  ('Chilischote', 'obst-gemuese'),
  ('Petersilie', 'obst-gemuese'),
  ('Basilikum', 'obst-gemuese'),
  ('Schnittlauch', 'obst-gemuese'),
  ('Dill', 'obst-gemuese'),
  ('Koriander', 'obst-gemuese'),
  ('Minze', 'obst-gemuese'),
  ('Rosmarin', 'obst-gemuese'),
  ('Thymian', 'obst-gemuese'),
  ('Salbei', 'obst-gemuese'),
  ('Zitrone', 'obst-gemuese'),
  ('Limette', 'obst-gemuese'),
  ('Orange', 'obst-gemuese'),
  ('Apfel', 'obst-gemuese'),
  ('Banane', 'obst-gemuese'),
  ('Birne', 'obst-gemuese'),
  ('Erdbeeren', 'obst-gemuese'),
  ('Himbeeren', 'obst-gemuese'),
  ('Blaubeeren', 'obst-gemuese'),
  ('Weintrauben', 'obst-gemuese'),
  ('Pfirsich', 'obst-gemuese'),
  ('Nektarine', 'obst-gemuese'),
  ('Pflaume', 'obst-gemuese'),
  ('Kirschen', 'obst-gemuese'),
  ('Mango', 'obst-gemuese'),
  ('Ananas', 'obst-gemuese'),
  ('Avocado', 'obst-gemuese'),
  ('Wassermelone', 'obst-gemuese'),
  ('Kiwi', 'obst-gemuese'),
  ('Datteln', 'obst-gemuese'),
  ('Feige', 'obst-gemuese'),
  ('Granatapfel', 'obst-gemuese'),
  ('Brot', 'backwaren'),
  ('Vollkornbrot', 'backwaren'),
  ('Toastbrot', 'backwaren'),
  ('Baguette', 'backwaren'),
  ('Brötchen', 'backwaren'),
  ('Fladenbrot', 'backwaren'),
  ('Tortillas', 'backwaren'),
  ('Wraps', 'backwaren'),
  ('Knäckebrot', 'backwaren'),
  ('Zwieback', 'backwaren'),
  ('Croissant', 'backwaren'),
  ('Burgerbrötchen', 'backwaren'),
  ('Rindergulasch', 'fleisch-fisch'),
  ('Rinderhackfleisch', 'fleisch-fisch'),
  ('Gemischtes Hackfleisch', 'fleisch-fisch'),
  ('Rinderfilet', 'fleisch-fisch'),
  ('Rumpsteak', 'fleisch-fisch'),
  ('Rinderbraten', 'fleisch-fisch'),
  ('Schweinefilet', 'fleisch-fisch'),
  ('Schweineschnitzel', 'fleisch-fisch'),
  ('Schweinebauch', 'fleisch-fisch'),
  ('Kasseler', 'fleisch-fisch'),
  ('Hähnchenbrust', 'fleisch-fisch'),
  ('Hähnchenschenkel', 'fleisch-fisch'),
  ('Hähnchenkeule', 'fleisch-fisch'),
  ('Ganzes Hähnchen', 'fleisch-fisch'),
  ('Putenbrust', 'fleisch-fisch'),
  ('Entenbrust', 'fleisch-fisch'),
  ('Lammkeule', 'fleisch-fisch'),
  ('Lammkotelett', 'fleisch-fisch'),
  ('Speck', 'fleisch-fisch'),
  ('Speckwürfel', 'fleisch-fisch'),
  ('Bacon', 'fleisch-fisch'),
  ('Schinken', 'fleisch-fisch'),
  ('Kochschinken', 'fleisch-fisch'),
  ('Serranoschinken', 'fleisch-fisch'),
  ('Salami', 'fleisch-fisch'),
  ('Bratwurst', 'fleisch-fisch'),
  ('Chorizo', 'fleisch-fisch'),
  ('Leberwurst', 'fleisch-fisch'),
  ('Lachsfilet', 'fleisch-fisch'),
  ('Kabeljau', 'fleisch-fisch'),
  ('Seelachs', 'fleisch-fisch'),
  ('Forelle', 'fleisch-fisch'),
  ('Garnelen', 'fleisch-fisch'),
  ('Muscheln', 'fleisch-fisch'),
  ('Tintenfisch', 'fleisch-fisch'),
  ('Räucherlachs', 'fleisch-fisch'),
  ('Milch', 'kuehlregal'),
  ('Vollmilch', 'kuehlregal'),
  ('H-Milch', 'kuehlregal'),
  ('Buttermilch', 'kuehlregal'),
  ('Kefir', 'kuehlregal'),
  ('Sahne', 'kuehlregal'),
  ('Schlagsahne', 'kuehlregal'),
  ('Crème fraîche', 'kuehlregal'),
  ('Schmand', 'kuehlregal'),
  ('Saure Sahne', 'kuehlregal'),
  ('Joghurt', 'kuehlregal'),
  ('Naturjoghurt', 'kuehlregal'),
  ('Griechischer Joghurt', 'kuehlregal'),
  ('Skyr', 'kuehlregal'),
  ('Quark', 'kuehlregal'),
  ('Magerquark', 'kuehlregal'),
  ('Frischkäse', 'kuehlregal'),
  ('Butter', 'kuehlregal'),
  ('Margarine', 'kuehlregal'),
  ('Butterschmalz', 'kuehlregal'),
  ('Eier', 'kuehlregal'),
  ('Gouda', 'kuehlregal'),
  ('Emmentaler', 'kuehlregal'),
  ('Bergkäse', 'kuehlregal'),
  ('Mozzarella', 'kuehlregal'),
  ('Feta', 'kuehlregal'),
  ('Parmesan', 'kuehlregal'),
  ('Pecorino', 'kuehlregal'),
  ('Ricotta', 'kuehlregal'),
  ('Mascarpone', 'kuehlregal'),
  ('Gorgonzola', 'kuehlregal'),
  ('Camembert', 'kuehlregal'),
  ('Brie', 'kuehlregal'),
  ('Halloumi', 'kuehlregal'),
  ('Reibekäse', 'kuehlregal'),
  ('Frische Hefe', 'kuehlregal'),
  ('Tofu', 'kuehlregal'),
  ('Räuchertofu', 'kuehlregal'),
  ('Blätterteig', 'kuehlregal'),
  ('Pizzateig', 'kuehlregal'),
  ('Hafermilch', 'kuehlregal'),
  ('Sojamilch', 'kuehlregal'),
  ('Mandelmilch', 'kuehlregal'),
  ('Hummus', 'kuehlregal'),
  ('TK-Erbsen', 'tiefkuehl'),
  ('TK-Spinat', 'tiefkuehl'),
  ('TK-Blattspinat', 'tiefkuehl'),
  ('TK-Beeren', 'tiefkuehl'),
  ('TK-Himbeeren', 'tiefkuehl'),
  ('TK-Gemüse', 'tiefkuehl'),
  ('Pommes frites', 'tiefkuehl'),
  ('Fischstäbchen', 'tiefkuehl'),
  ('Vanilleeis', 'tiefkuehl'),
  ('Blätterteig (TK)', 'tiefkuehl'),
  ('Tomatenmark', 'konserven'),
  ('Passierte Tomaten', 'konserven'),
  ('Gehackte Tomaten', 'konserven'),
  ('Dosentomaten', 'konserven'),
  ('Kokosmilch', 'konserven'),
  ('Kidneybohnen', 'konserven'),
  ('Kichererbsen (Dose)', 'konserven'),
  ('Weiße Bohnen', 'konserven'),
  ('Mais', 'konserven'),
  ('Oliven', 'konserven'),
  ('Kapern', 'konserven'),
  ('Gewürzgurken', 'konserven'),
  ('Sauerkraut', 'konserven'),
  ('Rotkohl (Glas)', 'konserven'),
  ('Thunfisch (Dose)', 'konserven'),
  ('Sardellen', 'konserven'),
  ('Erdnussbutter', 'konserven'),
  ('Marmelade', 'konserven'),
  ('Honig', 'konserven'),
  ('Apfelmus', 'konserven'),
  ('Pesto', 'konserven'),
  ('Ajvar', 'konserven'),
  ('Gemüsebrühe', 'konserven'),
  ('Rinderbrühe', 'konserven'),
  ('Hühnerbrühe', 'konserven'),
  ('Brühe', 'konserven'),
  ('Fond', 'konserven'),
  ('Tomatensauce', 'konserven'),
  ('Sardinen', 'konserven'),
  ('Nudeln', 'trockenware'),
  ('Spaghetti', 'trockenware'),
  ('Penne', 'trockenware'),
  ('Fusilli', 'trockenware'),
  ('Tagliatelle', 'trockenware'),
  ('Lasagneplatten', 'trockenware'),
  ('Spätzle', 'trockenware'),
  ('Reis', 'trockenware'),
  ('Basmatireis', 'trockenware'),
  ('Risottoreis', 'trockenware'),
  ('Milchreis', 'trockenware'),
  ('Couscous', 'trockenware'),
  ('Bulgur', 'trockenware'),
  ('Quinoa', 'trockenware'),
  ('Polenta', 'trockenware'),
  ('Haferflocken', 'trockenware'),
  ('Müsli', 'trockenware'),
  ('Cornflakes', 'trockenware'),
  ('Linsen', 'trockenware'),
  ('Rote Linsen', 'trockenware'),
  ('Belugalinsen', 'trockenware'),
  ('Semmelbrösel', 'trockenware'),
  ('Paniermehl', 'trockenware'),
  ('Mehl', 'trockenware'),
  ('Weizenmehl', 'trockenware'),
  ('Dinkelmehl', 'trockenware'),
  ('Vollkornmehl', 'trockenware'),
  ('Grieß', 'trockenware'),
  ('Speisestärke', 'trockenware'),
  ('Kartoffelstärke', 'trockenware'),
  ('Saucenbinder', 'trockenware'),
  ('Walnüsse', 'trockenware'),
  ('Haselnüsse', 'trockenware'),
  ('Mandeln', 'trockenware'),
  ('Gemahlene Mandeln', 'trockenware'),
  ('Cashewkerne', 'trockenware'),
  ('Pinienkerne', 'trockenware'),
  ('Sonnenblumenkerne', 'trockenware'),
  ('Kürbiskerne', 'trockenware'),
  ('Sesam', 'trockenware'),
  ('Leinsamen', 'trockenware'),
  ('Chiasamen', 'trockenware'),
  ('Rosinen', 'trockenware'),
  ('Trockenhefe', 'trockenware'),
  ('Backpulver', 'trockenware'),
  ('Natron', 'trockenware'),
  ('Kokosraspeln', 'trockenware'),
  ('Getrocknete Tomaten', 'trockenware'),
  ('Zucker', 'backen'),
  ('Puderzucker', 'backen'),
  ('Brauner Zucker', 'backen'),
  ('Vanillezucker', 'backen'),
  ('Vanilleschote', 'backen'),
  ('Vanilleextrakt', 'backen'),
  ('Zartbitterschokolade', 'backen'),
  ('Vollmilchschokolade', 'backen'),
  ('Kuvertüre', 'backen'),
  ('Schokoladenraspel', 'backen'),
  ('Kakaopulver', 'backen'),
  ('Marzipan', 'backen'),
  ('Gelatine', 'backen'),
  ('Agar-Agar', 'backen'),
  ('Ahornsirup', 'backen'),
  ('Agavendicksaft', 'backen'),
  ('Zuckerrübensirup', 'backen'),
  ('Rohrzucker', 'backen'),
  ('Salz', 'gewuerze'),
  ('Meersalz', 'gewuerze'),
  ('Pfeffer', 'gewuerze'),
  ('Paprikapulver', 'gewuerze'),
  ('Currypulver', 'gewuerze'),
  ('Kurkuma', 'gewuerze'),
  ('Kreuzkümmel', 'gewuerze'),
  ('Kümmel', 'gewuerze'),
  ('Koriandersamen', 'gewuerze'),
  ('Muskatnuss', 'gewuerze'),
  ('Zimt', 'gewuerze'),
  ('Nelken', 'gewuerze'),
  ('Kardamom', 'gewuerze'),
  ('Lorbeerblatt', 'gewuerze'),
  ('Wacholderbeeren', 'gewuerze'),
  ('Senfkörner', 'gewuerze'),
  ('Chiliflocken', 'gewuerze'),
  ('Cayennepfeffer', 'gewuerze'),
  ('Getrockneter Oregano', 'gewuerze'),
  ('Getrockneter Thymian', 'gewuerze'),
  ('Getrockneter Rosmarin', 'gewuerze'),
  ('Majoran', 'gewuerze'),
  ('Italienische Kräuter', 'gewuerze'),
  ('Kräuter der Provence', 'gewuerze'),
  ('Currypaste', 'gewuerze'),
  ('Olivenöl', 'gewuerze'),
  ('Rapsöl', 'gewuerze'),
  ('Sonnenblumenöl', 'gewuerze'),
  ('Sesamöl', 'gewuerze'),
  ('Kokosöl', 'gewuerze'),
  ('Essig', 'gewuerze'),
  ('Balsamico', 'gewuerze'),
  ('Weißweinessig', 'gewuerze'),
  ('Apfelessig', 'gewuerze'),
  ('Senf', 'gewuerze'),
  ('Dijonsenf', 'gewuerze'),
  ('Ketchup', 'gewuerze'),
  ('Mayonnaise', 'gewuerze'),
  ('Sojasauce', 'gewuerze'),
  ('Fischsauce', 'gewuerze'),
  ('Worcestershiresauce', 'gewuerze'),
  ('Tabasco', 'gewuerze'),
  ('Sriracha', 'gewuerze'),
  ('Harissa', 'gewuerze'),
  ('Tahini', 'gewuerze'),
  ('Zitronensaft', 'gewuerze'),
  ('Gemahlener Kreuzkümmel', 'gewuerze'),
  ('Mineralwasser', 'getraenke'),
  ('Rotwein', 'getraenke'),
  ('Weißwein', 'getraenke'),
  ('Sekt', 'getraenke'),
  ('Bier', 'getraenke'),
  ('Apfelsaft', 'getraenke'),
  ('Orangensaft', 'getraenke'),
  ('Tomatensaft', 'getraenke'),
  ('Kaffee', 'getraenke'),
  ('Espresso', 'getraenke'),
  ('Tee', 'getraenke'),
  ('Cola', 'getraenke'),
  ('Tonic Water', 'getraenke'),
  ('Wodka', 'getraenke'),
  ('Rum', 'getraenke'),
  ('Weinbrand', 'getraenke'),
  ('Portwein', 'getraenke'),
  ('Sherry', 'getraenke'),
  ('Mirin', 'getraenke'),
  ('Backpapier', 'haushalt'),
  ('Alufolie', 'haushalt'),
  ('Frischhaltefolie', 'haushalt'),
  ('Küchenrolle', 'haushalt'),
  ('Gefrierbeutel', 'haushalt'),
  ('Zahnstocher', 'haushalt'),
  ('Küchengarn', 'haushalt'),
  ('Müllbeutel', 'haushalt'),
  ('Spülmittel', 'haushalt')
) as t (name, category_id)
on conflict (name_norm) where household_id is null do update
  set category_id = excluded.category_id,
      display_name = excluded.display_name;
