-- AUTOMATISCH ERZEUGT von scripts/generate-ingredients-seed.mjs
-- Nicht von Hand bearbeiten: Quelle ist scripts/ingredient-seed-data.mjs.
-- Neu erzeugen mit: npm run seed:stammdaten

insert into categories (id, name, sort_order) values
  ('obst-gemuese', 'Obst & Gemüse', 10),
  ('backwaren', 'Brot & Backwaren', 20),
  ('fleisch-fisch', 'Fleisch & Fisch', 30),
  ('kuehlregal', 'Kühlregal', 40),
  ('tiefkuehl', 'Tiefkühl', 50),
  ('konserven', 'Konserven & Gläser', 60),
  ('trockenware', 'Nudeln, Reis & Trockenware', 70),
  ('backen', 'Backen & Süßes', 80),
  ('gewuerze', 'Gewürze und Öle', 90),
  ('getraenke', 'Getränke', 100),
  ('haushalt', 'Haushalt', 110),
  ('sonstiges', 'Sonstiges', 999)
on conflict (id) do update
  set name = excluded.name, sort_order = excluded.sort_order;

-- name_norm entsteht über die Funktion der Datenbank selbst, damit sie nicht von
-- der TypeScript-Seite abweichen kann.
insert into ingredients (household_id, name_norm, display_name, category_id, pantry_staple)
select null, normalize_ingredient_name(t.name), t.name, t.category_id, t.pantry_staple
from (values
  ('Zwiebel', 'obst-gemuese', false),
  ('Rote Zwiebel', 'obst-gemuese', false),
  ('Schalotte', 'obst-gemuese', false),
  ('Frühlingszwiebel', 'obst-gemuese', false),
  ('Knoblauch', 'obst-gemuese', false),
  ('Karotte', 'obst-gemuese', false),
  ('Möhre', 'obst-gemuese', false),
  ('Kartoffel', 'obst-gemuese', false),
  ('Süßkartoffel', 'obst-gemuese', false),
  ('Tomate', 'obst-gemuese', false),
  ('Cherrytomate', 'obst-gemuese', false),
  ('Paprika', 'obst-gemuese', false),
  ('Zucchini', 'obst-gemuese', false),
  ('Aubergine', 'obst-gemuese', false),
  ('Gurke', 'obst-gemuese', false),
  ('Lauch', 'obst-gemuese', false),
  ('Staudensellerie', 'obst-gemuese', false),
  ('Knollensellerie', 'obst-gemuese', false),
  ('Kohlrabi', 'obst-gemuese', false),
  ('Weißkohl', 'obst-gemuese', false),
  ('Rotkohl', 'obst-gemuese', false),
  ('Spitzkohl', 'obst-gemuese', false),
  ('Blumenkohl', 'obst-gemuese', false),
  ('Brokkoli', 'obst-gemuese', false),
  ('Rosenkohl', 'obst-gemuese', false),
  ('Wirsing', 'obst-gemuese', false),
  ('Spinat', 'obst-gemuese', false),
  ('Mangold', 'obst-gemuese', false),
  ('Feldsalat', 'obst-gemuese', false),
  ('Kopfsalat', 'obst-gemuese', false),
  ('Rucola', 'obst-gemuese', false),
  ('Eisbergsalat', 'obst-gemuese', false),
  ('Romanasalat', 'obst-gemuese', false),
  ('Champignons', 'obst-gemuese', false),
  ('Pilze', 'obst-gemuese', false),
  ('Pfifferlinge', 'obst-gemuese', false),
  ('Kürbis', 'obst-gemuese', false),
  ('Pastinake', 'obst-gemuese', false),
  ('Rote Bete', 'obst-gemuese', false),
  ('Radieschen', 'obst-gemuese', false),
  ('Rettich', 'obst-gemuese', false),
  ('Fenchel', 'obst-gemuese', false),
  ('Spargel', 'obst-gemuese', false),
  ('Grüne Bohnen', 'obst-gemuese', false),
  ('Zuckerschoten', 'obst-gemuese', false),
  ('Ingwer', 'obst-gemuese', false),
  ('Chilischote', 'obst-gemuese', false),
  ('Petersilie', 'obst-gemuese', false),
  ('Basilikum', 'obst-gemuese', false),
  ('Schnittlauch', 'obst-gemuese', false),
  ('Dill', 'obst-gemuese', false),
  ('Koriander', 'obst-gemuese', false),
  ('Minze', 'obst-gemuese', false),
  ('Rosmarin', 'obst-gemuese', false),
  ('Thymian', 'obst-gemuese', false),
  ('Salbei', 'obst-gemuese', false),
  ('Zitrone', 'obst-gemuese', false),
  ('Limette', 'obst-gemuese', false),
  ('Orange', 'obst-gemuese', false),
  ('Apfel', 'obst-gemuese', false),
  ('Banane', 'obst-gemuese', false),
  ('Birne', 'obst-gemuese', false),
  ('Erdbeeren', 'obst-gemuese', false),
  ('Himbeeren', 'obst-gemuese', false),
  ('Blaubeeren', 'obst-gemuese', false),
  ('Weintrauben', 'obst-gemuese', false),
  ('Pfirsich', 'obst-gemuese', false),
  ('Nektarine', 'obst-gemuese', false),
  ('Pflaume', 'obst-gemuese', false),
  ('Kirschen', 'obst-gemuese', false),
  ('Mango', 'obst-gemuese', false),
  ('Ananas', 'obst-gemuese', false),
  ('Avocado', 'obst-gemuese', false),
  ('Wassermelone', 'obst-gemuese', false),
  ('Kiwi', 'obst-gemuese', false),
  ('Datteln', 'obst-gemuese', false),
  ('Feige', 'obst-gemuese', false),
  ('Granatapfel', 'obst-gemuese', false),
  ('Brot', 'backwaren', false),
  ('Vollkornbrot', 'backwaren', false),
  ('Toastbrot', 'backwaren', false),
  ('Baguette', 'backwaren', false),
  ('Brötchen', 'backwaren', false),
  ('Fladenbrot', 'backwaren', false),
  ('Tortillas', 'backwaren', false),
  ('Wraps', 'backwaren', false),
  ('Knäckebrot', 'backwaren', false),
  ('Zwieback', 'backwaren', false),
  ('Croissant', 'backwaren', false),
  ('Burgerbrötchen', 'backwaren', false),
  ('Rindergulasch', 'fleisch-fisch', false),
  ('Rinderhackfleisch', 'fleisch-fisch', false),
  ('Gemischtes Hackfleisch', 'fleisch-fisch', false),
  ('Rinderfilet', 'fleisch-fisch', false),
  ('Rumpsteak', 'fleisch-fisch', false),
  ('Rinderbraten', 'fleisch-fisch', false),
  ('Schweinefilet', 'fleisch-fisch', false),
  ('Schweineschnitzel', 'fleisch-fisch', false),
  ('Schweinebauch', 'fleisch-fisch', false),
  ('Kasseler', 'fleisch-fisch', false),
  ('Hähnchenbrust', 'fleisch-fisch', false),
  ('Hähnchenschenkel', 'fleisch-fisch', false),
  ('Hähnchenkeule', 'fleisch-fisch', false),
  ('Ganzes Hähnchen', 'fleisch-fisch', false),
  ('Putenbrust', 'fleisch-fisch', false),
  ('Entenbrust', 'fleisch-fisch', false),
  ('Lammkeule', 'fleisch-fisch', false),
  ('Lammkotelett', 'fleisch-fisch', false),
  ('Speck', 'fleisch-fisch', false),
  ('Speckwürfel', 'fleisch-fisch', false),
  ('Bacon', 'fleisch-fisch', false),
  ('Schinken', 'fleisch-fisch', false),
  ('Kochschinken', 'fleisch-fisch', false),
  ('Serranoschinken', 'fleisch-fisch', false),
  ('Salami', 'fleisch-fisch', false),
  ('Bratwurst', 'fleisch-fisch', false),
  ('Chorizo', 'fleisch-fisch', false),
  ('Leberwurst', 'fleisch-fisch', false),
  ('Lachsfilet', 'fleisch-fisch', false),
  ('Kabeljau', 'fleisch-fisch', false),
  ('Seelachs', 'fleisch-fisch', false),
  ('Forelle', 'fleisch-fisch', false),
  ('Garnelen', 'fleisch-fisch', false),
  ('Muscheln', 'fleisch-fisch', false),
  ('Tintenfisch', 'fleisch-fisch', false),
  ('Räucherlachs', 'fleisch-fisch', false),
  ('Milch', 'kuehlregal', false),
  ('Vollmilch', 'kuehlregal', false),
  ('H-Milch', 'kuehlregal', false),
  ('Buttermilch', 'kuehlregal', false),
  ('Kefir', 'kuehlregal', false),
  ('Sahne', 'kuehlregal', false),
  ('Schlagsahne', 'kuehlregal', false),
  ('Crème fraîche', 'kuehlregal', false),
  ('Schmand', 'kuehlregal', false),
  ('Saure Sahne', 'kuehlregal', false),
  ('Joghurt', 'kuehlregal', false),
  ('Naturjoghurt', 'kuehlregal', false),
  ('Griechischer Joghurt', 'kuehlregal', false),
  ('Skyr', 'kuehlregal', false),
  ('Quark', 'kuehlregal', false),
  ('Magerquark', 'kuehlregal', false),
  ('Frischkäse', 'kuehlregal', false),
  ('Butter', 'kuehlregal', false),
  ('Margarine', 'kuehlregal', false),
  ('Butterschmalz', 'kuehlregal', false),
  ('Eier', 'kuehlregal', false),
  ('Gouda', 'kuehlregal', false),
  ('Emmentaler', 'kuehlregal', false),
  ('Bergkäse', 'kuehlregal', false),
  ('Mozzarella', 'kuehlregal', false),
  ('Feta', 'kuehlregal', false),
  ('Parmesan', 'kuehlregal', false),
  ('Pecorino', 'kuehlregal', false),
  ('Ricotta', 'kuehlregal', false),
  ('Mascarpone', 'kuehlregal', false),
  ('Gorgonzola', 'kuehlregal', false),
  ('Camembert', 'kuehlregal', false),
  ('Brie', 'kuehlregal', false),
  ('Halloumi', 'kuehlregal', false),
  ('Reibekäse', 'kuehlregal', false),
  ('Frische Hefe', 'kuehlregal', false),
  ('Tofu', 'kuehlregal', false),
  ('Räuchertofu', 'kuehlregal', false),
  ('Blätterteig', 'kuehlregal', false),
  ('Pizzateig', 'kuehlregal', false),
  ('Hafermilch', 'kuehlregal', false),
  ('Sojamilch', 'kuehlregal', false),
  ('Mandelmilch', 'kuehlregal', false),
  ('Hummus', 'kuehlregal', false),
  ('TK-Erbsen', 'tiefkuehl', false),
  ('TK-Spinat', 'tiefkuehl', false),
  ('TK-Blattspinat', 'tiefkuehl', false),
  ('TK-Beeren', 'tiefkuehl', false),
  ('TK-Himbeeren', 'tiefkuehl', false),
  ('TK-Gemüse', 'tiefkuehl', false),
  ('Pommes frites', 'tiefkuehl', false),
  ('Fischstäbchen', 'tiefkuehl', false),
  ('Vanilleeis', 'tiefkuehl', false),
  ('Blätterteig (TK)', 'tiefkuehl', false),
  ('Tomatenmark', 'konserven', false),
  ('Passierte Tomaten', 'konserven', false),
  ('Gehackte Tomaten', 'konserven', false),
  ('Dosentomaten', 'konserven', false),
  ('Kokosmilch', 'konserven', false),
  ('Kidneybohnen', 'konserven', false),
  ('Kichererbsen (Dose)', 'konserven', false),
  ('Weiße Bohnen', 'konserven', false),
  ('Mais', 'konserven', false),
  ('Oliven', 'konserven', false),
  ('Kapern', 'konserven', false),
  ('Gewürzgurken', 'konserven', false),
  ('Sauerkraut', 'konserven', false),
  ('Rotkohl (Glas)', 'konserven', false),
  ('Thunfisch (Dose)', 'konserven', false),
  ('Sardellen', 'konserven', false),
  ('Erdnussbutter', 'konserven', false),
  ('Marmelade', 'konserven', false),
  ('Honig', 'konserven', false),
  ('Apfelmus', 'konserven', false),
  ('Pesto', 'konserven', false),
  ('Ajvar', 'konserven', false),
  ('Fond', 'konserven', false),
  ('Tomatensauce', 'konserven', false),
  ('Sardinen', 'konserven', false),
  ('Nudeln', 'trockenware', false),
  ('Spaghetti', 'trockenware', false),
  ('Penne', 'trockenware', false),
  ('Fusilli', 'trockenware', false),
  ('Tagliatelle', 'trockenware', false),
  ('Lasagneplatten', 'trockenware', false),
  ('Spätzle', 'trockenware', false),
  ('Reis', 'trockenware', false),
  ('Basmatireis', 'trockenware', false),
  ('Risottoreis', 'trockenware', false),
  ('Milchreis', 'trockenware', false),
  ('Couscous', 'trockenware', false),
  ('Bulgur', 'trockenware', false),
  ('Quinoa', 'trockenware', false),
  ('Polenta', 'trockenware', false),
  ('Haferflocken', 'trockenware', false),
  ('Müsli', 'trockenware', false),
  ('Cornflakes', 'trockenware', false),
  ('Linsen', 'trockenware', false),
  ('Rote Linsen', 'trockenware', false),
  ('Belugalinsen', 'trockenware', false),
  ('Semmelbrösel', 'trockenware', false),
  ('Paniermehl', 'trockenware', false),
  ('Mehl', 'trockenware', false),
  ('Weizenmehl', 'trockenware', false),
  ('Dinkelmehl', 'trockenware', false),
  ('Vollkornmehl', 'trockenware', false),
  ('Grieß', 'trockenware', false),
  ('Speisestärke', 'trockenware', false),
  ('Kartoffelstärke', 'trockenware', false),
  ('Saucenbinder', 'trockenware', false),
  ('Walnüsse', 'trockenware', false),
  ('Haselnüsse', 'trockenware', false),
  ('Mandeln', 'trockenware', false),
  ('Gemahlene Mandeln', 'trockenware', false),
  ('Cashewkerne', 'trockenware', false),
  ('Pinienkerne', 'trockenware', false),
  ('Sonnenblumenkerne', 'trockenware', false),
  ('Kürbiskerne', 'trockenware', false),
  ('Sesam', 'trockenware', false),
  ('Leinsamen', 'trockenware', false),
  ('Chiasamen', 'trockenware', false),
  ('Rosinen', 'trockenware', false),
  ('Trockenhefe', 'trockenware', false),
  ('Backpulver', 'trockenware', false),
  ('Natron', 'trockenware', false),
  ('Kokosraspeln', 'trockenware', false),
  ('Getrocknete Tomaten', 'trockenware', false),
  ('Zucker', 'backen', false),
  ('Puderzucker', 'backen', false),
  ('Brauner Zucker', 'backen', false),
  ('Vanillezucker', 'backen', false),
  ('Vanilleschote', 'backen', false),
  ('Vanilleextrakt', 'backen', false),
  ('Zartbitterschokolade', 'backen', false),
  ('Vollmilchschokolade', 'backen', false),
  ('Kuvertüre', 'backen', false),
  ('Schokoladenraspel', 'backen', false),
  ('Kakaopulver', 'backen', false),
  ('Marzipan', 'backen', false),
  ('Gelatine', 'backen', false),
  ('Agar-Agar', 'backen', false),
  ('Ahornsirup', 'backen', false),
  ('Agavendicksaft', 'backen', false),
  ('Zuckerrübensirup', 'backen', false),
  ('Rohrzucker', 'backen', false),
  ('Salz', 'gewuerze', true),
  ('Meersalz', 'gewuerze', true),
  ('Pfeffer', 'gewuerze', true),
  ('Olivenöl', 'gewuerze', true),
  ('Rapsöl', 'gewuerze', false),
  ('Sonnenblumenöl', 'gewuerze', false),
  ('Sesamöl', 'gewuerze', false),
  ('Kokosöl', 'gewuerze', false),
  ('Essig', 'gewuerze', false),
  ('Balsamico', 'gewuerze', false),
  ('Weißweinessig', 'gewuerze', false),
  ('Apfelessig', 'gewuerze', false),
  ('Zitronensaft', 'gewuerze', false),
  ('Paprikapulver', 'gewuerze', false),
  ('Currypulver', 'gewuerze', false),
  ('Kurkuma', 'gewuerze', false),
  ('Kreuzkümmel', 'gewuerze', false),
  ('Kümmel', 'gewuerze', false),
  ('Koriandersamen', 'gewuerze', false),
  ('Muskatnuss', 'gewuerze', false),
  ('Zimt', 'gewuerze', false),
  ('Nelken', 'gewuerze', false),
  ('Kardamom', 'gewuerze', false),
  ('Lorbeerblatt', 'gewuerze', false),
  ('Wacholderbeeren', 'gewuerze', false),
  ('Senfkörner', 'gewuerze', false),
  ('Chiliflocken', 'gewuerze', false),
  ('Cayennepfeffer', 'gewuerze', false),
  ('Getrockneter Oregano', 'gewuerze', false),
  ('Getrockneter Thymian', 'gewuerze', false),
  ('Getrockneter Rosmarin', 'gewuerze', false),
  ('Majoran', 'gewuerze', false),
  ('Italienische Kräuter', 'gewuerze', false),
  ('Kräuter der Provence', 'gewuerze', false),
  ('Gemahlener Kreuzkümmel', 'gewuerze', false),
  ('Gemüsebrühe', 'gewuerze', false),
  ('Rinderbrühe', 'gewuerze', false),
  ('Hühnerbrühe', 'gewuerze', false),
  ('Brühe', 'gewuerze', false),
  ('Mineralwasser', 'getraenke', false),
  ('Rotwein', 'getraenke', false),
  ('Weißwein', 'getraenke', false),
  ('Sekt', 'getraenke', false),
  ('Bier', 'getraenke', false),
  ('Apfelsaft', 'getraenke', false),
  ('Orangensaft', 'getraenke', false),
  ('Tomatensaft', 'getraenke', false),
  ('Kaffee', 'getraenke', false),
  ('Espresso', 'getraenke', false),
  ('Tee', 'getraenke', false),
  ('Cola', 'getraenke', false),
  ('Tonic Water', 'getraenke', false),
  ('Wodka', 'getraenke', false),
  ('Rum', 'getraenke', false),
  ('Weinbrand', 'getraenke', false),
  ('Portwein', 'getraenke', false),
  ('Sherry', 'getraenke', false),
  ('Mirin', 'getraenke', false),
  ('Backpapier', 'haushalt', false),
  ('Alufolie', 'haushalt', false),
  ('Frischhaltefolie', 'haushalt', false),
  ('Küchenrolle', 'haushalt', false),
  ('Gefrierbeutel', 'haushalt', false),
  ('Zahnstocher', 'haushalt', false),
  ('Küchengarn', 'haushalt', false),
  ('Müllbeutel', 'haushalt', false),
  ('Spülmittel', 'haushalt', false),
  ('Currypaste', 'sonstiges', false),
  ('Senf', 'sonstiges', false),
  ('Dijonsenf', 'sonstiges', false),
  ('Ketchup', 'sonstiges', false),
  ('Mayonnaise', 'sonstiges', false),
  ('Sojasauce', 'sonstiges', false),
  ('Fischsauce', 'sonstiges', false),
  ('Worcestershiresauce', 'sonstiges', false),
  ('Tabasco', 'sonstiges', false),
  ('Sriracha', 'sonstiges', false),
  ('Harissa', 'sonstiges', false),
  ('Tahini', 'sonstiges', false)
) as t (name, category_id, pantry_staple)
on conflict (name_norm) where household_id is null do update
  set category_id = excluded.category_id,
      display_name = excluded.display_name,
      pantry_staple = excluded.pantry_staple;
